### PR TITLE
build 1.4.51

### PR DESCRIPTION
**Pull request by boldorider4**
sqlalchemy 1.4.51

**Destination channel:** defaults

### Links

- [PKG-3732] 
- [Upstream repository](https://github.com/sqlalchemy/sqlalchemy/tree/rel_1_4_51)
- [Upstream changelog/diff](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_51/doc/build/changelog/changelog_14.rst)

### Explanation of changes:

- this older release is required by this [PR](https://github.com/AnacondaRecipes/splink-feedstock/pull/2)

[PKG-3732]: https://anaconda.atlassian.net/browse/PKG-3732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Comment by rafaelmartins** [comment]
while publishing older versions is fine, the master/main branch should point at the most recent one. I think that you need a versioned feedstock for this.

**Comment by M-Waszkiewicz-Anaconda** [comment]
> while publishing older versions is fine, the master/main branch should point at the most recent one. I think that you need a versioned feedstock for this.

I think it is there already
commit b069c605d5026a31af211719a0b509eb28ed8c3d
Author: Jack Olivieri <jolivieri@anaconda.com>
Date:   Wed Jan 3 17:49:36 2024 +0100

    sqlalchemy-1.4.51-feedstock: add new submodule

**Comment by rafaelmartins** [comment]
> > while publishing older versions is fine, the master/main branch should point at the most recent one. I think that you need a versioned feedstock for this.
> 
> I think it is there already commit b069c605d5026a31af211719a0b509eb28ed8c3d Author: Jack Olivieri [jolivieri@anaconda.com](mailto:jolivieri@anaconda.com) Date: Wed Jan 3 17:49:36 2024 +0100
> 
> ```
> sqlalchemy-1.4.51-feedstock: add new submodule
> ```

then this pr is open in the wrong repo, or at least pointing to the wrong branch... this should not be proposed to merge to master here.

**Comment by boldorider4** [comment]
> > > while publishing older versions is fine, the master/main branch should point at the most recent one. I think that you need a versioned feedstock for this.
> > 
> > 
> > I think it is there already commit b069c605d5026a31af211719a0b509eb28ed8c3d Author: Jack Olivieri [jolivieri@anaconda.com](mailto:jolivieri@anaconda.com) Date: Wed Jan 3 17:49:36 2024 +0100
> > ```
> > sqlalchemy-1.4.51-feedstock: add new submodule
> > ```
> 
> then this pr is open in the wrong repo, or at least pointing to the wrong branch... this should not be proposed to merge to master here.

Correct! Thanks for catching that!

**Review by rafaelmartins — APPROVED** [review]

**Pull request merged**
